language: php

php:
  - 5.6
  - 7.0
  - hhvm

before_install:
  - composer self-update
  - composer validate

install:
  - composer install --prefer-source

script:
  - vendor/bin/phpcs --standard=psr2 src tests
  - vendor/bin/php-cs-fixer fix --verbose --dry-run src tests
  - vendor/bin/phpunit

matrix:
  fast_finish: true
